name: Upload Objdiff Progress Report Artifact

on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MKPVE01_report
          path: ./report.json
